// <auto-generated />
using System;
using Cheetos.vviki.WebAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Cheetos.vviki.WebAPI.Migrations
{
    [DbContext(typeof(VVikiContext))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Cheetos.vviki.WebAPI.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Page");
                });

            modelBuilder.Entity("Cheetos.vviki.WebAPI.Paragraph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("Paragraph");
                });

            modelBuilder.Entity("Cheetos.vviki.WebAPI.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Cheetos.vviki.WebAPI.Paragraph", b =>
                {
                    b.HasOne("Cheetos.vviki.WebAPI.Page", null)
                        .WithMany("Paragraphs")
                        .HasForeignKey("PageId");
                });

            modelBuilder.Entity("Cheetos.vviki.WebAPI.Tag", b =>
                {
                    b.HasOne("Cheetos.vviki.WebAPI.Page", null)
                        .WithMany("Tags")
                        .HasForeignKey("PageId");
                });
#pragma warning restore 612, 618
        }
    }
}
